config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # auth user
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Defines the root path route ("/")
  root "home#index"

  # new recipe form
  get 'recipes/new', to: 'recipes#new', as: :new_recipe

  # post new recipe
  post 'recipes/create/:user_id', to: 'recipes#create', as: :create_recipe

  # recent recipe list
  get 'recipes/recent', to: 'recipes#index', as: :recipes

  # recipe detail
  get 'recipe/:id', to: 'recipes#show', as: :show_recipe

  # show recipe list every category
  get 'category/:id', to: 'categories#show', as: :show_category

  # search recipe
  get 'search', to: 'recipes#search', as: :search_recipes

  # show profile
  get 'users/profile/:id', to: 'users#show_profile', as: :user_profile

  # show user recipes
  get 'users/recipes/:id', to: 'users#show_recipes', as: :user_recipes

  # like recipe
  post 'users/:id/recipes/:recipe_id/like', to: 'likes#like_recipe', as: :like_recipe

  # unlike recipe
  delete 'users/:id/recipes/:recipe_id/unlike', to: 'likes#unlike_recipe', as: :unlike_recipe

  # user's liked recipes
  get 'users/likes/:id', to: 'users#show_likes', as: :user_likes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # relation
  belongs_to :category
  belongs_to :user
  has_many :materials, dependent: :destroy
  has_many :flows, dependent: :destroy
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  accepts_nested_attributes_for :materials, allow_destroy: true
  accepts_nested_attributes_for :flows, allow_destroy: true
  mount_uploader :image, ImageUploader

  # validation
  validates :title,
            presence: true,
            length: { in: 3..30 }
  validates :comment,
            length: { maximum: 300 }
  validates :tips,
            length: { maximum: 300 }
  validates :upbringing,
            length: { maximum: 300 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i(index show)
  before_action :init_recipe

  def new
  end

  def create
    user = User.find(params[:user_id])
    @recipe = user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to root_path, notice: '新しいレシピを投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @recipes = Recipe.page(params[:page]).per(20)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def search
    @recipes = @q.result.page(params[:page]).per(30)
  end


  # private
  def recipe_params
    params.require(:recipe).permit(
      :title,
      :image,
      :comment,
      :tips,
      :upbringing,
      :category_id,
      materials_attributes: [:name, :_destroy],
      flows_attributes: [:body, :_destroy]
    )
  end

  def init_recipe
    @recipe = Recipe.new
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: '新着レシピ'
} %>

<div class="recipe">
  <div class="recipe__inner">
    <h2 class="recipe__heading">新着レシピ</h2>
    <div class="recipe__contents">
      <% @recipes.each do |recipe| %>
      <div class="recipe__flex flex">
        <div class="recipe__flex-item before">
          <% if recipe.image? %>
          <%= image_tag recipe.image.url %>
          <% else %>
          <%= image_tag 'img_food01.jpg' %>
          <% end %>
        </div>
        <div class="recipe__flex-item after">
          <%= link_to '#', class: 'contents' do %>
          <h3><%= recipe.title %></h3>
          <% end %>
          <span><span>by</span>&nbsp;<%= link_to recipe.user.name, '#', class: 'contents' %></span>
          <p><%= recipe.comment %></p>
          <p>
            <% if recipe.materials.any? %>
            材料:&nbsp;<%= recipe.materials[0].name %>
            <% else %>
            材料:&nbsp;無し
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
      <%= paginate @recipes %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: '新規レシピ投稿'
} %> <%= form_with model: @recipe, url: create_recipe_path(current_user), class:
'form-recipe', html: { novalidate: true }, local: true do |new_recipe| %>
<h2 class="form-recipe__heading">レシピを書く</h2>

<%= render "shared/error_messages", object: new_recipe.object %>

<div class="form-recipe__item">
  <%= new_recipe.label :title, 'レシピのタイトル', class: 'form-recipe__label'
  %><br />
  <%= new_recipe.text_field :title, class: 'form-recipe__input' %>
</div>

<div class="form-recipe__item flex">
  <div class="form-recipe__input--file before">
    <label>
      <span title="ファイルを選択">
        <%= image_tag 'ico_camera.png', alt: '+画像' %>
        クリックして料理の写真をのせる
      </span>
      <%= new_recipe.file_field :image %>
    </label>
  </div>
  <div class="after">
    <%= new_recipe.label :comment, 'レシピに添える一言', class:
    'form-recipe__label' %><br />
    <%= new_recipe.text_area :comment, class: 'form-recipe__textarea', rows: 5 %> <%= new_recipe.fields_for :materials, @recipe.materials.build do |material| %> <%= label_tag :name, '材料(カンマで区切ってください)', class: 'form-recipe__label' %><br /><%= material.text_area :name, class: 'form-recipe__textarea', rows: 5 %> <% end %>
  </div>
</div>
<div class="form-recipe__item">
  <h3 class="form-recipe__item-heading">作り方</h3>
  <table class="form-recipe__table" id="form-recipe-table">
    <%= new_recipe.fields_for :flows, @recipe.flows.build do |flow| %>
    <tbody>
      <tr>
        <td class="first"><%= flow.text_area :body, rows: 3 %></td>
        <td class="secondary"><%= button_tag type: 'button', class: 'form-recipe__btn', onclick: 'deleteRow(this)' do %>
          削除
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= button_tag type: 'button', class: 'form-recipe__btn add' do %>
  手順を追加
  <% end %>
</div>
<div class="form-recipe__item flex">
  <div class="form-recipe__item--before">
    <%= new_recipe.label :tips, 'コツ・ポイント', class:
    'form-recipe__label' %><br />
    <%= new_recipe.text_area :tips, class: 'form-recipe__textarea', rows: 5
    %>
  </div>
  <div class="form-recipe__item--after">
    <%= new_recipe.label :upbringing, 'このレシピの生い立ち', class:
    'form-recipe__label' %><br />
    <%= new_recipe.text_area :upbringing, class: 'form-recipe__textarea', rows: 5
    %>
  </div>
</div>
<div class="form-recipe__item">
  <%= new_recipe.label :category_id, 'カテゴリー', class: 'form-recipe__label' %><br>
  <%= new_recipe.collection_select :category_id, Category.all, :id, :name, options = { include_blank: '選択してください' }, { class: 'form-recipe__select' , required: true } %>
</div>
<div class="form-recipe__item">
  <%= new_recipe.submit 'レシピを投稿する', class: 'form-recipe__submit' %>
</div>
<% end %>

app/views/recipes/search.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: @q.title_or_comment_cont
} %>

<div class="recipe">
  <div class="recipe__inner">
    <h2 class="recipe__heading">「<%= @q.title_or_comment_cont %>」の検索結果</h2>
    <div class="recipe__contents">
      <% if @recipes.any? %>
      <% @recipes.each do |recipe| %>
      <div class="recipe__flex flex">
        <div class="recipe__flex-item before">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <% if recipe.image? %>
          <%= image_tag recipe.image.url %>
          <% else %>
          <%= image_tag 'img_food01.jpg' %>
          <% end %>
          <% end %>
        </div>
        <div class="recipe__flex-item after">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <h3><%= recipe.title %></h3>
          <% end %>
          <span><span>by</span>&nbsp;<%= link_to recipe.user.name, '#', class: 'contents' %></span>
          <p><%= recipe.comment %></p>
          <p>
            <% if recipe.materials.any? %>
            材料:&nbsp;<%= recipe.materials[0].name %>
            <% else %>
            材料:&nbsp;無し
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
      <%= paginate @recipes %>
      <% else %>
      <p class="recipe__txt">検索結果はありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: @recipe.title + ' by ' + @recipe.user.name
} %>

<div class="recipe-show">
  <div class="recipe-show__inner">
    <h2 class="recipe-show__heading">
      <%= @recipe.title %>
    </h2>
    <div class="recipe-show__flex flex first">
      <div class="recipe-show__flex-item before">
        <% if @recipe.image? %>
        <%= image_tag @recipe.image.url %>
        <% else %>
        <%= image_tag 'img_food01.jpg' %>
        <% end %>
      </div>
      <div class="recipe-show__flex-item after">
        <p><%= @recipe.comment %></p>
        <% if check_exists_likes(@recipe.id) %>
        <%= button_to '保存を外す', unlike_recipe_path(current_user, @recipe), method: :delete, class: 'recipe-show__btn remove' %>
        <% else %>
        <%= button_to 'レシピを保存', like_recipe_path(current_user, @recipe), method: :post, class: 'recipe-show__btn' %>
        <% end %>
        <p>
          <% if @recipe.user.profile_image? %>
          <%= image_tag @recipe.user.profile_image.url %>
          <% else %>
          <%= image_tag 'img_profile.jpg' %>
          <% end %>
          &nbsp;
          <%= @recipe.user.name %>
        </p>
        <dl>
          <dt class="recipe-show__sub-heading">材料</dt>
          <dd class="recipe-show__txt"><%= @recipe.materials[0].name %></dd>
        </dl>
      </div>
    </div>
    <div>
      <h3 class="recipe-show__sub-heading">作り方</h3>
      <p class="recipe-show__txt"><%= @recipe.flows[0].body %></p>
    </div>
    <div class="recipe-show__flex flex secondary">
      <dl class="recipe-show__flex-item before">
        <dt class="recipe-show__sub-heading">コツ・ポイント</dt>
        <dd class="recipe-show__txt"><%= @recipe.tips %></dd>
      </dl>
      <dl class="recipe-show__flex-item after">
        <dt class="recipe-show__sub-heading">このレシピの生い立ち</dt>
        <dd class="recipe-show__txt"><%= @recipe.upbringing %></dd>
      </dl>
    </div>
    <span class="recipe-show__data">レシピID:&nbsp;<%= @recipe.id %>&nbsp;公開日:&nbsp;<%= l @recipe.created_at %></span>
  </div>
</div>