config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # auth user
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Defines the root path route ("/")
  root "home#index"

  # new recipe form
  get 'recipes/new', to: 'recipes#new', as: :new_recipe

  # post new recipe
  post 'recipes/create/:user_id', to: 'recipes#create', as: :create_recipe

  # recent recipe list
  get 'recipes/recent', to: 'recipes#index', as: :recipes

  # recipe detail
  get 'recipe/:id', to: 'recipes#show', as: :show_recipe

  # show recipe list every category
  get 'category/:id', to: 'categories#show', as: :show_category

  # search recipe
  get 'search', to: 'recipes#search', as: :search_recipes

  # show profile
  get 'users/profile/:id', to: 'users#show_profile', as: :user_profile

  # show user recipes
  get 'users/recipes/:id', to: 'users#show_recipes', as: :user_recipes

  # like recipe
  post 'users/:id/recipes/:recipe_id/like', to: 'likes#like_recipe', as: :like_recipe

  # unlike recipe
  delete 'users/:id/recipes/:recipe_id/unlike', to: 'likes#unlike_recipe', as: :unlike_recipe

  # user's liked recipes
  get 'users/likes/:id', to: 'users#show_likes', as: :user_likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # validation
  validates :name,
            presence: true,
            length: { in: 3..30 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # relation
  has_many :recipes
  has_many :likes
  has_many :like_recipes, through: :likes, source: :recipe
  mount_uploader :profile_image, ProfileImageUploader
  mount_uploader :profile_bg_image, ProfileBackGroundImageUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image, :profile_bg_image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image, :profile_bg_image])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show_profile
    @latest_recipes = @user.recipes.order(id: :desc).limit(5)

    render :profile
  end

  def show_recipes
    @recipes = @user.recipes

    render :recipes
  end

  def show_likes
    @recipes = @user.like_recipes

    render :likes
  end

  # private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/likes.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: @user.name + 'のフォルダ一覧'
} %>

<div class="recipe">
  <div class="recipe__inner">
    <h2 class="recipe__heading"><%= @user.name %>のフォルダ一覧&nbsp;(<%= @recipes.count %>件)</h2>
    <div class="recipe__contents">
      <% @recipes.each do |recipe| %>
      <div class="recipe__flex flex">
        <div class="recipe__flex-item before">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <% if recipe.image? %>
          <%= image_tag recipe.image.url %>
          <% else %>
          <%= image_tag 'img_food01.jpg' %>
          <% end %>
          <% end %>
        </div>
        <div class="recipe__flex-item after">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <h3><%= recipe.title %></h3>
          <% end %>
          <span><span>by</span>&nbsp;<%= link_to recipe.user.name, user_profile_path(recipe.user.id), class: 'contents' %></span>
          <p><%= recipe.comment %></p>
          <p>
            <% if recipe.materials.any? %>
            材料:&nbsp;<%= recipe.materials[0].name %>
            <% else %>
            材料:&nbsp;無し
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: @user.name + 'のキッチン'
} %>

<div class="profile">
  <div class="profile__upper">
    <div class="profile__bg-img">
      <% if @user.profile_bg_image? %>
      <%= image_tag @user.profile_bg_image.url %>
      <% else %>
      <%= image_tag 'img_cooking.jpg' %>
      <% end %>
    </div>
    <div class="profile__upper-flex flex">
      <div class="profile__upper-flex-item before">
        <% if @user.profile_image? %>
        <%= image_tag @user.profile_image.url %>
        <% else %>
        <%= image_tag 'img_profile.jpg' %>
        <% end %>
      </div>
      <p class="profile__upper-flex-item after">
        <%= @user.name %>さん<span>のキッチン</span>
      </p>
    </div>
  </div>
  <div class="profile__lower">
    <h2 class="profile__heading">レシピ<span>(<%= @user.recipes.size %>品)</span><%= link_to 'レシピ一覧>>', user_recipes_path(@user), class: 'profile__link' %></h2>
    <div class="profile__lower-flex flex">
      <% if @latest_recipes.any? %>
      <% @latest_recipes.each_with_index do |recipe, i| %>
      <%= link_to show_recipe_path(recipe), class: 'profile__lower-flex-link' do %>
      <figure class="profile__lower-flex-item">
        <% if recipe.image? %>
        <%= image_tag recipe.image.url %>
        <% else %>
        <%= image_tag recipe.image %>
        <% end %>
      </figure>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/recipes.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: @user.name + 'のレシピ一覧'
} %>

<div class="recipe">
  <div class="recipe__inner">
    <h2 class="recipe__heading"><%= @user.name %>のレシピ一覧&nbsp;(<%= @recipes.count %>件)</h2>
    <div class="recipe__contents">
      <% @recipes.each do |recipe| %>
      <div class="recipe__flex flex">
        <div class="recipe__flex-item before">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <% if recipe.image? %>
          <%= image_tag recipe.image.url %>
          <% else %>
          <%= image_tag 'img_food01.jpg' %>
          <% end %>
          <% end %>
        </div>
        <div class="recipe__flex-item after">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <h3><%= recipe.title %></h3>
          <% end %>
          <span><span>by</span>&nbsp;<%= link_to recipe.user.name, user_profile_path(recipe.user.id), class: 'contents' %></span>
          <p><%= recipe.comment %></p>
          <p>
            <% if recipe.materials.any? %>
            材料:&nbsp;<%= recipe.materials[0].name %>
            <% else %>
            材料:&nbsp;無し
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>