config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # auth user
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Defines the root path route ("/")
  root "home#index"

  # new recipe form
  get 'recipes/new', to: 'recipes#new', as: :new_recipe

  # post new recipe
  post 'recipes/create/:user_id', to: 'recipes#create', as: :create_recipe

  # recent recipe list
  get 'recipes/recent', to: 'recipes#index', as: :recipes

  # recipe detail
  get 'recipe/:id', to: 'recipes#show', as: :show_recipe

  # show recipe list every category
  get 'category/:id', to: 'categories#show', as: :show_category

  # search recipe
  get 'search', to: 'recipes#search', as: :search_recipes

  # show profile
  get 'users/profile/:id', to: 'users#show_profile', as: :user_profile

  # show user recipes
  get 'users/recipes/:id', to: 'users#show_recipes', as: :user_recipes

  # like recipe
  post 'users/:id/recipes/:recipe_id/like', to: 'likes#like_recipe', as: :like_recipe

  # unlike recipe
  delete 'users/:id/recipes/:recipe_id/unlike', to: 'likes#unlike_recipe', as: :unlike_recipe

  # user's liked recipes
  get 'users/likes/:id', to: 'users#show_likes', as: :user_likes
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # relation
  has_many :recipes
end

app/models/flow.rb
class Flow < ApplicationRecord
  # relation
  belongs_to :recipe

  validates :body,
            presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  # relation
  belongs_to :user
  belongs_to :recipe

  # validation
  # validates :user_id, uniqueness: { scope: :recipe_id }
end

app/models/material.rb
class Material < ApplicationRecord
  # relation
  belongs_to :recipe

  # validation
  validates :name,
            presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # relation
  belongs_to :category
  belongs_to :user
  has_many :materials, dependent: :destroy
  has_many :flows, dependent: :destroy
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  accepts_nested_attributes_for :materials, allow_destroy: true
  accepts_nested_attributes_for :flows, allow_destroy: true
  mount_uploader :image, ImageUploader

  # validation
  validates :title,
            presence: true,
            length: { in: 3..30 }
  validates :comment,
            length: { maximum: 300 }
  validates :tips,
            length: { maximum: 300 }
  validates :upbringing,
            length: { maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # validation
  validates :name,
            presence: true,
            length: { in: 3..30 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # relation
  has_many :recipes
  has_many :likes
  has_many :like_recipes, through: :likes, source: :recipe
  mount_uploader :profile_image, ProfileImageUploader
  mount_uploader :profile_bg_image, ProfileBackGroundImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_q

  def set_q
    @q = Recipe.ransack(params[:q])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes.page(params[:page]).per(30)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.limit(12).order(id: :desc)
    @categories = Category.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def like_recipe
    user = User.find(params[:id])
    recipe = Recipe.find(params[:recipe_id])

    user.like_recipes << recipe
    redirect_to request.referer, notice: 'マイフォルダに追加しました'
  end

  def unlike_recipe
    @res = Like.where(user_id: params[:id]).find_by(recipe_id: params[:recipe_id])
    @res.destroy

    redirect_to request.referer, notice: 'マイフォルダから削除しました'
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i(index show)
  before_action :init_recipe

  def new
  end

  def create
    user = User.find(params[:user_id])
    @recipe = user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to root_path, notice: '新しいレシピを投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @recipes = Recipe.page(params[:page]).per(20)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def search
    @recipes = @q.result.page(params[:page]).per(30)
  end


  # private
  def recipe_params
    params.require(:recipe).permit(
      :title,
      :image,
      :comment,
      :tips,
      :upbringing,
      :category_id,
      materials_attributes: [:name, :_destroy],
      flows_attributes: [:body, :_destroy]
    )
  end

  def init_recipe
    @recipe = Recipe.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show_profile
    @latest_recipes = @user.recipes.order(id: :desc).limit(5)

    render :profile
  end

  def show_recipes
    @recipes = @user.recipes

    render :recipes
  end

  def show_likes
    @recipes = @user.like_recipes

    render :likes
  end

  # private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "レシピ検索No.1／料理レシピ載せるなら パイパッド".freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} - #{BASE_TITLE}"
    end
  end

  # 現在表示しているページが利用登録またはログインページか確認する
  def check_if_authpage
    controller_name == 'registrations' || controller_name == 'sessions'
  end

  # 現在表示しているページがレシピページか確認する
  def check_if_recipepage
    controller_name == 'recipes'
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def check_exists_likes(recipe_id)
    user = current_user
    res = user.like_recipes.where(id: recipe_id)
    res.any?
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def output_class_name(name)
    case name
    when '野菜のおかず'
      'veggie'
    when 'お肉のおかず'
      'meat'
    when '魚介のおかず'
      'fish'
    when 'ごはんもの'
      'rice'
    when 'パスタ・グラタン'
      'pasta'
    when '麺'
      'noodles'
    when 'サラダ'
      'salad'
    when 'スープ・汁物'
      'soup'
    when 'お弁当'
      'bento'
    when 'おもてなし料理'
      'omotenashi'
    when 'お菓子'
      'snack'
    when 'パン'
      'bread'
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "main", "data-turbo-track": "reload", defer: true %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <!-- header -->
  <% if check_if_authpage || check_if_recipepage %>
  <%= render 'shared/header_auth' %>
  <% else %>
  <%= render 'shared/header_main' %>
  <% end %>

  <!-- flash message -->
  <% if flash[:notice] %>
  <p class="flash-msg notice"><%= notice %></p>
  <% end %>
  <% if flash[:alert] %>
  <p class="flash-msg alert"><%= alert %></p>
  <% end %>

  <!-- main -->
  <main class="main">
    <div class="wrap">
      <%= yield %>
    </div>
  </main>

  <!-- footer -->
  <% if check_if_authpage || check_if_recipepage %>
  <%= render 'shared/footer_auth' %>
  <% else %>
  <%= render 'shared/footer_main' %>
  <% end %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="alert alert-warning">
  <ul class="err-msg">
    <% object.errors.full_messages.each do |message| %>
    <li class="err-msg__item"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer_auth.html.erb
<footer class="footer-auth">
  <ul class="footer-auth__menu flex">
    <li class="footer-auth__item">
      <%= link_to '特定商取引法に基づく表示', '#' %>
    </li>
    <li class="footer-auth__item">
      <%= link_to '利用規約', '#' %>
    </li>
    <li class="footer-auth__item">
      <%= link_to 'プライバシーポリシー', '#' %>
    </li>
    <li class="footer-auth__item">
      <%= link_to 'お問い合わせ', '#' %>
    </li>
  </ul>
  <small class="footer-auth__copyr"
    >Copyright&copy; Paipad Inc. All Rights Reserved</small
  >
</footer>

app/views/shared/_footer_main.html.erb
<footer class="footer">
  <div class="wrap">
    <div class="footer__upper flex">
      <dl class="footer__upper-list">
        <dt class="footer__upper-title recipe-h">レシピをさがす</dt>
        <dd class="footer__upper-item">
          <%= link_to 'カテゴリ一覧', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to '話題のレシピ', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to '人気の検索キーワード', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to '新着レシピ', recipes_path %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'デイリーアクセス数ランキング', '#' %>
        </dd>
      </dl>
      <dl class="footer__upper-list">
        <dt class="footer__upper-title write">レシピを書く</dt>
        <dd class="footer__upper-item">
          <%= link_to 'レシピを書く', new_recipe_path %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'レシピの書き方について', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to '企業・団体キッチンの登録', '#' %>
        </dd>
        <dt class="footer__upper-title secondary menu">献立</dt>
        <dd class="footer__upper-item">
          <%= link_to 'みんなの献立', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'プレミアム献立', '#' %>
        </dd>
      </dl>
      <dl class="footer__upper-list">
        <dt class="footer__upper-title suggest">おすすめ</dt>
        <dd class="footer__upper-item">
          <%= link_to 'モバイルサービス', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'パイパッドニュース', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'パイパッドのレシピ本', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to '料理の基本', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'パイパッドブログ', '#' %>
        </dd>
        <dt class="footer__upper-title secondary premium">
          プレミアムサービス
        </dt>
        <dd class="footer__upper-item">
          <%= link_to 'プレミアムサービス', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'プレミアムクーポン', '#' %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'プレミアムパス', '#' %>
        </dd>
      </dl>
      <dl class="footer__upper-list">
        <dt class="footer__upper-title user">あなたのページ</dt>
        <% if user_signed_in? %>
        <dd class="footer__upper-item">
          <%= link_to current_user.name + 'さん',
          user_profile_path(current_user) %>
        </dd>
        <% else %>
        <dd class="footer__upper-item">
          <%= link_to 'ユーザー登録(無料)', new_user_registration_path %>
        </dd>
        <dd class="footer__upper-item">
          <%= link_to 'ログイン', new_user_session_path %>
        </dd>
        <% end %>
      </dl>
    </div>
    <div class="footer__lower">
      <div class="footer__lower-flex flex">
        <h3 class="footer__lower-flex-title">サポート</h3>
        <ul class="footer__lower-flex-list flex">
          <li class="footer__lower-flex-item">
            <%= link_to 'ヘルプ', '#' %>
          </li>
          <li class="footer__lower-flex-item">
            <%= link_to '料理の安心', '#' %>
          </li>
          <li class="footer__lower-flex-item">
            <%= link_to '利用規約等', '#' %>
          </li>
          <li class="footer__lower-flex-item">
            <%= link_to 'リンクについて', '#' %>
          </li>
        </ul>
      </div>
      <div class="footer__lower-flex flex">
        <h3 class="footer__lower-flex-title">企業情報</h3>
        <ul class="footer__lower-flex-list flex">
          <li class="footer__lower-flex-item">
            <%= link_to '運営会社', '#' %>
          </li>
          <li class="footer__lower-flex-item">
            <%= link_to 'プライバシーポリシー', '#' %>
          </li>
          <li class="footer__lower-flex-item">
            <%= link_to '広告掲載', '#' %>
          </li>
          <li class="footer__lower-flex-item">
            <%= link_to '採用情報', '#' %>
          </li>
        </ul>
      </div>
      <div class="footer__lower-flex flex">
        <h3 class="footer__lower-flex-title">日本</h3>
        <ul class="footer__lower-flex-list flex last">
          <li class="footer__lower-flex-item">
            <%= link_to 'Español', '#' %>
          </li>
          <li class="footer__lower-flex-item">
            <%= link_to 'English', '#' %>
          </li>
        </ul>
      </div>
      <small class="footer__copyr"
        >Copyright&copy; Paipad Inc. All Rights Reserved</small
      >
      <figure class="footer__img">
        <%= image_tag 'img_footer01.png' %>
      </figure>
    </div>
  </div>
</footer>

app/views/shared/_header_auth.html.erb
<header class="header-auth">
  <div class="header-auth__inner">
    <div class="wrap">
      <h1 class="header-auth__logo">
        <%= link_to image_tag('logo_paipad.png'), root_path %>
      </h1>
    </div>
  </div>
</header>

app/views/shared/_header_main.html.erb
<header class="header-main">
  <div class="header-main__upper">
    <div class="wrap">
      <div class="header-main__upper-inner flex">
        <h2 class="header-main__upper-heading">毎日の料理を楽しみにする</h2>
        <ul class="header-main__upper-menu flex">
          <li class="header-main__upper-item">
            <%= link_to 'プレミアムサービス', '#', class:
            'header-main__upper-link premium' %>
          </li>
          <% if user_signed_in? %>
          <li class="header-main__upper-item">
            <%= link_to current_user.name + 'さん', user_profile_path(current_user), class:
            'header-main__upper-link' %>
          </li>
          <li class="header-main__upper-item">
            <%= link_to 'ログアウト', destroy_user_session_path, class:
            'header-main__upper-link' %>
          </li>
          <% else %>
          <li class="header-main__upper-item">
            <%= link_to 'ユーザー登録(無料)', new_user_registration_path, class:
            'header-main__upper-link' %>
          </li>
          <li class="header-main__upper-item">
            <%= link_to 'ログイン', new_user_session_path, class:
            'header-main__upper-link' %>
          </li>
          <% end %>
        </ul>
        <figure class="header-main__upper-item sm"><%= image_tag 'ico_menu_sp.png', class: 'header-main__upper-ico' %></figure>
      </div>
    </div>
  </div>
  <div class="header-main__lower">
    <div class="wrap">
      <div class="header-main__lower-inner flex">
        <h1 class="header-main__lower-logo">
          <%= link_to image_tag('logo_paipad.png'), root_path %>
          <div class="header-main__lower-label-wrap">
            <div class="header-main__lower-label">
              <span><%= Recipe.count %>件</span><br />レシピ
            </div>
          </div>
        </h1>
        <%= search_form_for @q, url: search_recipes_path, class:
        'header-main__lower-form' do |search| %>
        <%= search.text_field :title_or_comment_cont, placeholder: '料理名・食材名' %> <%= search.submit 'レシピ検索' %> <% end %>
        <ul class="header-main__lower-links flex">
          <li class="header-main__lower-item">
            <%= link_to 'MYフォルダ', user_likes_path(current_user), class: 'header-main__lower-link gray'
            %>
          </li>
          <li class="header-main__lower-item">
            <%= link_to 'レシピを書く', new_recipe_path, class:
            'header-main__lower-link green' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_page_title.html.erb
<% provide(:title, page_title) %>

app/views/shared/_sp_menu.html.erb
<ul class="sp-menu">
  <li class="sp-menu__item"><%= link_to 'プレミアムサービス', '#', class: 'sp-menu__link' %></li>
  <% if user_signed_in? %>
  <li class="sp-menu__item">
    <%= link_to current_user.name + 'さん', user_profile_path(current_user), class: 'sp-menu__link' %>
  </li>
  <li class="sp-menu__item">
    <%= link_to 'ログアウト', destroy_user_session_path, class: 'sp-menu__link' %>
  </li>
  <li class="sp-menu__item">
    <%= link_to 'MYフォルダ', user_likes_path(current_user), class: 'sp-menu__link' %>
  </li>
  <li class="sp-menu__item">
    <%= link_to 'レシピを書く', new_recipe_path, class: 'sp-menu__link' %>
  </li>
  <% else %>
  <li class="sp-menu__item">
    <%= link_to 'ユーザー登録(無料)', new_user_registration_path, class:
 'sp-menu__link' %>
  </li>
  <li class="sp-menu__item">
    <%= link_to 'ログイン', new_user_session_path, class:
 'sp-menu__link' %>
  </li>
  <% end %>
</ul>
<div class="sp-menu__overlay"></div>