config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # auth user
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Defines the root path route ("/")
  root "home#index"

  # new recipe form
  get 'recipes/new', to: 'recipes#new', as: :new_recipe

  # post new recipe
  post 'recipes/create/:user_id', to: 'recipes#create', as: :create_recipe

  # recent recipe list
  get 'recipes/recent', to: 'recipes#index', as: :recipes

  # recipe detail
  get 'recipe/:id', to: 'recipes#show', as: :show_recipe

  # show recipe list every category
  get 'category/:id', to: 'categories#show', as: :show_category

  # search recipe
  get 'search', to: 'recipes#search', as: :search_recipes

  # show profile
  get 'users/profile/:id', to: 'users#show_profile', as: :user_profile

  # show user recipes
  get 'users/recipes/:id', to: 'users#show_recipes', as: :user_recipes

  # like recipe
  post 'users/:id/recipes/:recipe_id/like', to: 'likes#like_recipe', as: :like_recipe

  # unlike recipe
  delete 'users/:id/recipes/:recipe_id/unlike', to: 'likes#unlike_recipe', as: :unlike_recipe

  # user's liked recipes
  get 'users/likes/:id', to: 'users#show_likes', as: :user_likes
end

app/models/category.rb
class Category < ApplicationRecord
  # relation
  has_many :recipes
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes.page(params[:page]).per(30)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def check_exists_likes(recipe_id)
    user = current_user
    res = user.like_recipes.where(id: recipe_id)
    res.any?
  end
end

app/views/categories/show.html.erb
<!-- ページタイトル -->
<%= render partial: 'shared/page_title', locals: { page_title: @category.name + 'のレシピ一覧'
} %>

<div class="recipe">
  <div class="recipe__inner">
    <h2 class="recipe__heading">「<%= @category.name %>」のレシピ一覧</h2>
    <div class="recipe__contents">
      <% @recipes.each do |recipe| %>
      <div class="recipe__flex flex">
        <div class="recipe__flex-item before">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <% if recipe.image? %>
          <%= image_tag recipe.image.url %>
          <% else %>
          <%= image_tag 'img_food01.jpg' %>
          <% end %>
          <% end %>
        </div>
        <div class="recipe__flex-item after">
          <%= link_to show_recipe_path(recipe), class: 'contents' do %>
          <h3><%= recipe.title %></h3>
          <% end %>
          <span><span>by</span>&nbsp;<%= link_to recipe.user.name, user_profile_path(recipe.user.id), class: 'contents' %></span>
          <% if check_exists_likes(recipe.id) %>
          <%= button_to '保存を外す', unlike_recipe_path(current_user, recipe), method: :delete, class: 'recipe-show__btn remove' %>
          <% else %>
          <%= button_to 'レシピを保存', like_recipe_path(current_user, recipe), method: :post, class: 'recipe-show__btn' %>
          <% end %>
          <p><%= recipe.comment %></p>
          <p>
            <% if recipe.materials.any? %>
            材料:&nbsp;<%= recipe.materials[0].name %>
            <% else %>
            材料:&nbsp;無し
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
      <%= paginate @recipes %>
    </div>
  </div>
</div>